name: testing

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: hooopo/repo-track-pipeline@v1.0.2
        with:
          name: ttt 
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          database_url: ${{ secrets.DATABASE_URL }}
          repo-full-name: ${{ secrets.REPO_FULL_NAME }}
