name: testing

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:      
    - name: hello
      uses: hooopo/repo-track-pipeline@v1.0.10
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        REPO_FULL_NAME: ${{ secrets.REPO_FULL_NAME }}
