name: testing

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:      
    - name: hello
      uses: hooopo/repo-track-pipeline@v1.0.6
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }} 
        database_url: ${{ secrets.DATABASE_URL }}
        repo_full_name: ${{ secrets.REPO_FULL_NAME }}
